services:
  redis:
    image: redis:latest
    container_name: redis_mail_service
    ports:
      - "6379:6379"
    restart: always

  mail-service:
    build: ../mail-service
    container_name: mail_service
    depends_on:
      - redis
    env_file:
      - .env

    ports:
      - "50052:50052"
    restart: always