services:
  redis:
    image: redis:latest
    container_name: redis_mail_service
    ports:
      - "6379:6379"
    restart: always

  mail-service:
    build: ../mail-service
    container_name: mail_service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=ta_cle_api_resend
      - EMAIL_FROM=no-reply@tondomaine.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "50052:50052"
    restart: always